// Links to assets uploaded on cloudinary to make work easier with v0
export const ASSETS = {
  "accessories.svg": "/accessories.svg",
  "apple.png": "/apple.png",
  "apple-store.svg": "/apple-store.svg",
  "auction-black.svg": "/auction-black.svg",
  "auction-white.svg": "/auction-white.svg",
  "bank-black.svg": "/bank-black.svg",
  "bar-graph-black.svg": "/bar-graph-black.svg",
  "box-black.svg": "/box-black.svg",
  "camera.svg": "/camera.svg",
  "chat-black.svg": "/chat-black.svg",
  "check.svg": "/check.svg",
  "clock-black.svg": "/clock-black.svg",
  "clock-gray.svg": "/clock-gray.svg",
  "cloth-1.png": "/cloth-1.png",
  "cloth-2.png": "/cloth-2.png",
  "coupon-black.svg": "/coupon-black.svg",
  "credit-card-white.svg": "/credit-card-white.svg",
  "cross-white.svg": "/cross-white.svg",
  "crown-black.svg": "/crown-black.svg",
  "delivery-black.svg": "/delivery-black.svg",
  "diners-club-logo.webp": "/diners-club-logo.webp",
  "directions-black.svg": "/directions-black.svg",
  "edit-black.svg": "/edit-black.svg",
  "facebook.png": "/facebook.png",
  "facebook-white.svg": "/facebook-white.svg",
  "file-plus-black.svg": "/file-plus-black.svg",
  "flash-black.svg": "/flash-black.svg",
  "flash-green.svg": "/flash-green.svg",
  "flash-white.svg": "/flash-white.svg",
  "gallery.png": "/gallery.png",
  "google.png": "/google.png",
  "google-play.svg": "/google-play.svg",
  "header-1.png": "/header-1.png",
  "header-2.jpg": "/header-2.jpg",
  "heart.svg": "/heart.svg",
  "heart-black.svg": "/heart-black.svg",
  "history-black.svg": "/history-black.svg",
  "instagram-white.svg": "/instagram-white.svg",
  "location.svg": "/location.svg",
  "location-black.svg": "/location-black.svg",
  "logout-black.svg": "/logout-black.svg",
  "mastercard-logo.webp": "/mastercard-logo.webp",
  "menu-black.svg": "/menu-black.svg",
  "message-black.svg": "/message-black.svg",
  "offer-black.svg": "/offer-black.svg",
  "out-link.svg": "/out-link.svg",
  "out-link-black.svg": "/out-link-black.svg",
  "padlock-white.svg": "/padlock-white.svg",
  "pants.svg": "/pants.svg",
  "person-1.png": "/person-1.png",
  "person-2.png": "/person-2.png",
  "placeholder.svg": "/placeholder.svg",
  "placeholder-logo.svg": "/placeholder-logo.svg",
  "placeholder-profile-pic.png": "/placeholder-profile-pic.png",
  "plus-white.svg": "/plus-white.svg",
  "polos.svg": "/polos.svg",
  "print-white.svg": "/print-white.svg",
  "search-black.svg": "/search-black.svg",
  "search-white.svg": "/search-white.svg",
  "shoes.svg": "/shoes.svg",
  "shopping-cart-black.svg": "/shopping-cart-black.svg",
  "shopping-cart-black-2.svg": "/shopping-cart-black-2.svg",
  "size-guide-black.svg": "/size-guide-black.svg",
  "star.svg": "/star.svg",
  "star-black.svg": "/star-black.svg",
  "stripe.svg": "/stripe.svg",
  "tick-black.svg": "/tick-black.svg",
  "trash-black.svg": "/trash-black.svg",
  "trash-solid-black.svg": "/trash-solid-black.svg",
  "trophy.svg": "/trophy.svg",
  "zecond-logo-black.png": "/zecond-logo-black.png",
  "zecond-logo-white.png": "/zecond-logo-white.png",
  "twitter-white.svg": "/twitter-white.svg",
  "update-black.svg": "/update-black.svg",
  "user-1.svg": "/user-1.svg",
  "user-2.svg": "/user-2.svg",
  "user-3.svg": "/user-3.svg",
  "visa-logo.webp": "/visa-logo.webp",
  "wallet-black.svg": "/wallet-black.svg",
  "zecond-banner-desktop.jpg": "/zecond-banner-desktop.jpg",
  "zecond-banner-mobile.jpg": "/zecond-banner-mobile.jpg",
} as const;

export const SHIPPING_COST = 50;

export const MexicanBanks = [
  "ABC Capital",
  "Accendo Banco",
  "Actinver",
  "Afirme Grupo Financiero",
  "Agrofinanzas",
  "American Express Bank",
  "Banca Afirme",
  "Banca Mifel",
  "Banco Ahorro Famsa",
  "Banco Amigo",
  "Banco Autofin",
  "Banco Azteca",
  "Banco BASE",
  "Banco Covalto",
  "Banco de Mexico",
  "Banco del Bajio",
  "Banco del Bienestar",
  "Banco Facil (Chedraui)",
  "Banco Famsa",
  "Banco Forjadores",
  "Banco Inmobiliario Mexicano",
  "Banco Interacciones",
  "Banco Invex",
  "Banco Monex",
  "Banco Multiva",
  "Banco Ve X +",
  "Banco Volkswagen Mexico",
  "Bancomext",
  "Bancoppel",
  "BanCoppel",
  "Bancrea",
  "BanJercito",
  "Banobras",
  "Banorte",
  "BanRegio",
  "Bansi S.A.",
  "Bansefi",
  "BanBajio",
  "Bank of America Mexico",
  "Bank of China",
  "Bank Saderat Iran",
  "Bankaool",
  "Barclays Mexico",
  "BBVA Mexico",
  "CI Banco",
  "Citibanamex",
  "Compartamos Banco",
  "Consubanco",
  "Credit Suisse",
  "Deutsche Bank",
  "Financiera Rural",
  "Fundacion Donde Banco",
  "HSBC Mexico",
  "Industrial and Commercial Bank of China",
  "Inbursa",
  "ING Mexico",
  "Intercam",
  "Invex",
  "Ixe Banco",
  "J.P. Morgan Chase",
  "Mizuho Bank Mexico",
  "MUFG",
  "Nafin",
  "Pagatodo",
  "Santander Mexico",
  "Scotiabank Mexico",
  "SHF",
  "Shinhan Bank",
  "UBS Bank",
];
